--A company has provided sales data containing information about customer purchases
--Your task is to:
--1. Calculate Total Revenue
--2. Calculate Total Sales by Product
--3. Find Top Customers by Revenue
--Market Analysis using SQL
--So let’s solve all these problems one by one for the task of Market Analysis using SQL.
CREATE TABLE Sales (
    CustomerID INT,
    ProductID CHAR(1),
    PurchaseDate DATE,
    Quantity INT,
    Revenue DECIMAL(10, 2)
);

INSERT INTO Sales (CustomerID, ProductID, PurchaseDate, Quantity, Revenue)
VALUES
    (1, 'A', '2023-01-01', 5, 100),
    (2, 'B', '2023-01-02', 3, 50),
    (3, 'A', '2023-01-03', 2, 30),
    (4, 'C', '2023-01-03', 1, 20),
    (1, 'B', '2023-01-04', 4, 80);

--Calculating total revenue:
SELECT SUM(Revenue) AS TotalRevenue FROM Sales;

--This query calculates the total revenue earned from all the sales recorded in the “Sales” table. It does so by adding the values in the “Revenue” column. The result of this calculation is given the name “TotalRevenue” for better identification and reference.
--Calculating total sales by product:
SELECT ProductID, SUM(Quantity) AS TotalQuantity, SUM(Revenue) AS TotalRevenue
FROM Sales
GROUP BY ProductID;
--This query retrieves information from the “Sales” table and calculates the total quantity sold and revenue generated for each product. By grouping the data based on the unique product IDs, the query calculates the sum of the quantities and revenues associated with each product. The results are presented with the respective product IDs, total quantities, and total revenues for further analysis or reporting.
--Finding top customers by revenue:
SELECT CustomerID, SUM(Revenue) AS TotalRevenue
FROM Sales
GROUP BY CustomerID
ORDER BY TotalRevenue DESC
LIMIT 5;
--This query retrieves information from the “Sales” table and calculates the total revenue generated by each customer. By grouping the data based on the unique customer IDs, the query calculates the sum of the revenues associated with each customer. The results are then sorted in descending order based on the total revenue and limited to the top 5 rows, allowing us to identify the customers with the highest total revenues.
  
